apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: drawio
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: ./kubernetes/services/drawio/my-drawio
      valuesFiles:
        - ./kubernetes/services/drawio/my-drawio/dev-values.yaml
        - ./kubernetes/services/drawio/my-drawio/staging-values.yaml
        - ./kubernetes/services/drawio/my-drawio/prod-values.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system