services:
  mc:
    image: itzg/minecraft-server:latest
    pull_policy: daily
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: "4096M"
      MAX_PLAYERS: "5"
      MOTD: "Future home of placing blocs and shi?"
      ICON: "https://i.imgur.com/Qx3XL5o.png"
      USE_MEOWICE_FLAGS: "true"
      DIFFICULTY: "3"
    volumes:
      - /mnt/docker-nfs/volumes/minecraft-data:/data

  newt:
    image: fosrl/newt
    container_name: newt-minecraft
    restart: unless-stopped
    env_file: .env