apiVersion: apps/v1
kind: Deployment
metadata:
  name: bytestash
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bytestash
  template:
    metadata:
      labels:
        app: bytestash
    spec:
      containers:
      - name: bytestash
        image: ghcr.io/jordan-dalby/bytestash:1.5.11@sha256:0b18d858623855e34cf14354c360e155cb742c46c17e843a85b978ce8af83396
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: bytestash-data
          mountPath: /data/snippets
      volumes:
      - name: bytestash-data
        persistentVolumeClaim:
          claimName: bytestash-nfs-pvc
