apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: bytestash-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`bytestash.kube-demo-1.mistyfumes.dev`)
      kind: Rule
      services:
        - name: bytestash
          port: 5000
  tls:
    certResolver: cloudflare