services:
  app:
    image: ghcr.io/hargata/lubelogger:v1.6.0@sha256:96ef62ba38370d38eb01dce5419324f81545caef55eccb0c48860aacde08d513
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/lubelogger-data:/App/data
      - /mnt/docker-nfs/volumes/lubelogger-data/keys:/root/.aspnet/DataProtection-Keys
    # ports:
    #   - 8080:8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lubelogger-insecure.rule=Host(`lubelogger.mistyfumes.dev`)"
      - "traefik.http.routers.lubelogger-insecure.entrypoints=http"
      - "traefik.http.routers.lubelogger-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.lubelogger-secure.rule=Host(`lubelogger.mistyfumes.dev`)"
      - "traefik.http.routers.lubelogger-secure.entrypoints=https"
      - "traefik.http.routers.lubelogger-secure.tls=true"
      - "traefik.http.routers.lubelogger-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.lubelogger.loadbalancer.server.port=8080"
    networks: 
      - frontend

networks:
  frontend:
    external: true