services:
  app:
    image: ghcr.io/hargata/lubelogger:latest
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/lubelogger-data:/App/data
      - /mnt/docker-nfs/volumes/lubelogger-data/keys:/root/.aspnet/DataProtection-Keys
    ports:
      - 8080:8080