apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-postgres-deployment.yaml
  - authentik-postgres-pvc.yaml
  - authentik-postgres-svc.yaml
  - authentik-sealed-secret.yaml