apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-db
  template:
    metadata:
      labels:
        app: kaneo-db
    spec:
      containers:
        - name: kaneo-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
          - secretRef:
              name: kaneo-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: kaneo-database
      volumes:
        - name: kaneo-database
          persistentVolumeClaim:
            claimName: kaneo-nfs-pvc