apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaneo-web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaneo-web
  template:
    metadata:
      labels:
        app: kaneo-web
    spec:
      containers:
        - name: kaneo-web
          image: ghcr.io/usekaneo/web:2.2.1@sha256:130aa1b98eea13164fe48c2982a53a2170f6c08d363fc57c682d0edfe9d388a1
          ports:
            - containerPort: 5173
          env:
            - name: KANEO_CLIENT_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_CLIENT_URL
            - name: KANEO_API_URL
              valueFrom:
                configMapKeyRef:
                  name: kaneo-configmap
                  key: KANEO_API_URL