services:
  postgresql:
    environment:
      POSTGRES_DB: ${PG_DB:-authentik}
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      PGDATA: /var/lib/postgresql/data/pgdata
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/authentik-data/authentik-db:/var/lib/postgresql/data

  server:
    command: server
    depends_on:
      postgresql:
        condition: service_started
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ghcr.io/goauthentik/server:2025.10.3@sha256:c2f132826e5b33629800cdd045a33ed9d80599538aaa49ad290397399539be9d
    ports:
      - ${COMPOSE_PORT_HTTP:-9000}:9000
      - ${COMPOSE_PORT_HTTPS:-9443}:9443
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/authentik-data/media:/media
      - /mnt/docker-nfs/volumes/authentik-data/custom-templates:/templates
      
  worker:
    command: worker
    depends_on:
      postgresql:
        condition: service_started
    environment:
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ghcr.io/goauthentik/server:2025.10.3@sha256:c2f132826e5b33629800cdd045a33ed9d80599538aaa49ad290397399539be9d
    restart: unless-stopped
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-nfs/volumes/authentik-data/media:/media
      - /mnt/docker-nfs/volumes/authentik-data/certs:/certs
      - /mnt/docker-nfs/volumes/authentik-data/custom-templates:/templates