services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:29.3.2@sha256:9ff2a16ef243c59510a395ea927fe156ce5f8eb5e8dbfbcfbd9b6d62e045541f
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio-insecure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-insecure.entrypoints=http"
      - "traefik.http.routers.drawio-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.drawio-secure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-secure.entrypoints=https"
      - "traefik.http.routers.drawio-secure.tls=true"
      - "traefik.http.routers.drawio-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.drawio.loadbalancer.server.port=8080"
    networks: 
      - frontend

networks:
  frontend:
    external: true