services:
  drawio:
    container_name: drawio
    image: jgraph/drawio:29.3.6@sha256:c7c7f7912c2eb5e747978ad4d62a7f21c129df457d2e9711d0abc235993fdfa2
    # ports:
    #   - 8080:8080
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drawio-insecure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-insecure.entrypoints=http"
      - "traefik.http.routers.drawio-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.drawio-secure.rule=Host(`drawio.mistyfumes.dev`)"
      - "traefik.http.routers.drawio-secure.entrypoints=https"
      - "traefik.http.routers.drawio-secure.tls=true"
      - "traefik.http.routers.drawio-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.drawio.loadbalancer.server.port=8080"
    networks: 
      - frontend

networks:
  frontend:
    external: true