apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-secrets
  namespace: default
spec:
  encryptedData:
    DB_PASS: AgBuTGCLB3kcGzql+e9kN3qTHls9tqYj5OEHobysD7hiNd8x24OdhUB342ES+NBc8FAd3htcA3axn/IptaXOyH+5LX3Z9u5eO/O1xVmjaL8pCalTiG7ntgKxdJ1IJELIFOJjdpHow6azu1wlXR4sKFEXeRck7U2FttkzPIBtzinTR24sF2Leuf26no+dOyfNd88Sv9FzVwsKUkP4zSMkXn2WbNU3kcQDk1zERVTLhT6bLIiVvSzEu9+3ER8gTM68CdaA1n4UPmMhTlzRfi8P+Tj/jhKjTHzbvTSjWyhclKe+yo+a1KfVlciry+JVXC0KjCiK2iAci/P+ULzJbVBSJX1HedhzytOgi679Jo27Zlxngbj0vqas4KljYf3VDzqu64eE1iP+CsLgs35UK6b/PbsIfHFNZ7BFIJhIXknM9oWUFNtvtrBHm1ohXJW11hMwxvZJAqOBrRuqzkS1H2/v6FEOvNgSDHYDrj2KyksWUOc9BMuAS8J5RVwFeCGieT4pBxsbUDiQnfQrLJ1V5Tqt8rf4gGDBXWZMyrbDJXoaEUfipF8fUEBdAFajmLKsqZEAkFphb1q/OE43/2AhVYuh9FlbH4VuRzsmfTWxvBuOkLzzZlQPMB9W4Nylx1Lv1WOZVZ2NAs3iVP4QdpagEGH2rLpK0Ke3HfBL1r3E7dmwdVW8T7BOBRlRvS7dinN9USIFGW+lQ0El508snqe8U1D4pMNjZArUGIOWBKjt5IL0y2WboH3fBsGQp1MyMO822aPV2Vg=
    secret_key: AgBykGVP8iySbaRGt1ivOjF/5uZXQ++2Dp6XVhGg4KXCXdbxdCoC/uqEPbmh3WpA8c4vd2A38dkNLyFpE4PObZLsvpZ4XdB6z1/dUx7XFdMULhFIcl3GKwb3SiUkb7aT8CjxZwSlKFBF8kZWMhaLmhZnKEvwwwfdgiVcQOPQ9PsftDLq4j8aty+7Nt1+caAZ/v0f4RL7EIs8G7SAL3vi5gUtt3W40SeUjXqTR1U/UXDwckuAUmnHaY2bo/Lm+J4G7IN7rLYqpuk5SCBSHOONFOPvThBTHt6p8m5Meh4d0DdS5bEmslgWk09hUych0Zl0z209sAeLiZC1UCEItqCGs154kKn1r5rJ6ghITGPWF3UGmU36fYYJ7RiCmviqd0qNmK9emdrNddnfoYKBtcXbYCP1zYaLA3aUxm7plu9J1KoWWwSnV0T1lwxoHKtuc/EH5BiHOHI2Y190cYuI8jNufjNowDxSejaJcOY9PqrDsfMAtfU95bBejkm95gPufwEjsmofJLgDcS3+VvL53e5lfrePGenuSzwcMVLT0JJlFj00FpAujgaPDfCP4heGQRrVVbwNUE+XUoHB7gg9qGN8Hxq7wEmni+neMal93mkpn2OsnsvqCI8xj3f1pW7BTwvVTjoaRBitont16bxGNrWlQthms189+ZbD37mL/Ps9mlZ4xkHaKNzQInXIlyAYI8hcv/TuRYraeNVRfyuB43E0RwHulkyGShFQ3muFbKcR4xQq79FwxqScga85l68sEpQT1HRqvWbiLjqIW64m850BSPHZp0iWnvDZ2bQCAy8ZMM7XpA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-secrets
      namespace: default
---
