services:
  composetoolbox:
    image: ghcr.io/bluegoosemedia/composetoolbox:main@sha256:3a1ab9c39d8932acff75b8df7f21bea96a3bdfa8a65f1747d787f63997ca5490
    # ports:
    #   - 3000:3000
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/compose-toolbox/data:/app/data
    labels:
      - "traefik.enable=true"
      # HTTP router
      - "traefik.http.routers.composetoolbox-insecure.rule=Host(`compose-toolbox.mistyfumes.dev`)"
      - "traefik.http.routers.composetoolbox-insecure.entrypoints=http"
      - "traefik.http.routers.composetoolbox-insecure.middlewares=https-redirect@file"
      # HTTPS router
      - "traefik.http.routers.composetoolbox-secure.rule=Host(`compose-toolbox.mistyfumes.dev`)"
      - "traefik.http.routers.composetoolbox-secure.entrypoints=https"
      - "traefik.http.routers.composetoolbox-secure.tls=true"
      - "traefik.http.routers.composetoolbox-secure.tls.certresolver=cloudflare"
      # Service port
      - "traefik.http.services.composetoolbox.loadbalancer.server.port=3000"
    networks:
      - frontend

networks:
  frontend:
    external: true