services:
  adguard-dns-visualizer:
      image: 'azwanngali/adguard-dns-visualizer:latest'
      environment:
        ADGUARD_URL: ${ADGUARD_URL}
        ADGUARD_USERNAME: ${ADGUARD_USERNAME}
        ADGUARD_PASSWORD: ${ADGUARD_PASSWORD}
        SOURCE_LAT: ${SOURCE_LAT}
        SOURCE_LNG: ${SOURCE_LNG}
      ports:
        - '8100:8080'
      container_name: dns-visualizer