services:
  beszel:
    image: henrygd/beszel:0.18.3@sha256:d1326b5cd73838b1d1acc5f1764c4b993c9668aa26df149082695894cb2805ae
    container_name: beszel
    restart: unless-stopped
    # ports:
    #   - 8090:8090
    environment:
      APP_URL: https://beszel.mistyfumes.dev
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_data:/beszel_data
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel-insecure.rule=Host(`beszel.mistyfumes.dev`)
      - traefik.http.routers.beszel-insecure.entrypoints=http
      - traefik.http.routers.beszel-insecure.middlewares=https-redirect@file
      - traefik.http.routers.beszel-secure.rule=Host(`beszel.mistyfumes.dev`)
      - traefik.http.routers.beszel-secure.entrypoints=https
      - traefik.http.routers.beszel-secure.tls=true
      - traefik.http.routers.beszel-secure.tls.certresolver=cloudflare
      - traefik.http.services.beszel.loadbalancer.server.port=8090
    networks:
      - frontend

  beszel-agent:
    image: henrygd/beszel-agent:0.18.3@sha256:67b51e7976da13b7ce15e0270869827d54aa3df8cf0978e240e4105f62395a46
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_agent_data:/var/lib/beszel-agent
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.mistyfumes.dev
      TOKEN: ${TOKEN}
      KEY: ${KEY}

networks:
  frontend:
    external: true