services:
  beszel:
    image: henrygd/beszel:0.18.3@sha256:d1326b5cd73838b1d1acc5f1764c4b993c9668aa26df149082695894cb2805ae
    container_name: beszel
    restart: unless-stopped
    # ports:
    #   - 8090:8090
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_data:/beszel_data
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel-insecure.rule=Host(`beszel.mistyfumes.dev`)
      - traefik.http.routers.beszel-insecure.entrypoints=http
      - traefik.http.routers.beszel-insecure.middlewares=https-redirect@file
      - traefik.http.routers.beszel-secure.rule=Host(`beszel.mistyfumes.dev`)
      - traefik.http.routers.beszel-secure.entrypoints=https
      - traefik.http.routers.beszel-secure.tls=true
      - traefik.http.routers.beszel-secure.tls.certresolver=cloudflare
      - traefik.http.services.beszel.loadbalancer.server.port=8090
    networks:
      - frontend

  beszel-agent:
    image: henrygd/beszel-agent:0.17.0@sha256:730ac49d1a89d315b5a9424ad8cca2f586e981da7caf151c5ec2d599f474efad
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_agent_data:/var/lib/beszel-agent
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.mistyfumes.dev
      TOKEN: ${TOKEN}
      KEY: ${KEY}
      
networks:
  frontend:
    external: true