services:
  beszel:
    image: henrygd/beszel:0.17.0@sha256:185142e6c91bd44c77fef6cd31784aee0f782eb1d7193c3ee34a9902a936621c
    container_name: beszel
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_data:/beszel_data
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket

  beszel-agent:
    image: henrygd/beszel-agent:0.17.0@sha256:730ac49d1a89d315b5a9424ad8cca2f586e981da7caf151c5ec2d599f474efad
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /mnt/docker-nfs/volumes/bezel-data/beszel_agent_data:/var/lib/beszel-agent
      - /mnt/docker-nfs/volumes/bezel-data/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: https://beszel.mistyfumes.dev
      TOKEN: ${TOKEN}
      KEY: ${KEY}