services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/paperless-data/redisdata:/data
    networks:
      - default

  paperless-db:
    image: docker.io/library/postgres:18
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/paperless-data/pgdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.20.6@sha256:a28330462994b937938e02aaa5632a1effcc7f9acfba96c1bef9c50e1167a027
    restart: unless-stopped
    depends_on:
      - paperless-db
      - broker
      - gotenberg
      - tika
    # ports:
    #   - "8000:8000"
    volumes:
      - /mnt/docker-nfs/volumes/paperless-data/data:/usr/src/paperless/data
      - /mnt/docker-nfs/volumes/paperless-data/media:/usr/src/paperless/media
      - /mnt/docker-nfs/volumes/paperless-data/export:/usr/src/paperless/export
      - /mnt/docker-nfs/volumes/paperless-data/consume:/usr/src/paperless/consume
    environment:
      USERMAP_UID: ${USERMAP_UID}
      USERMAP_GID: ${USERMAP_GID}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: ${PAPERLESS_DBHOST}
      PAPERLESS_DBUSER: ${POSTGRES_USER}
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD} 
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_REVERSE_PROXY_AUTH: ${PAPERLESS_REVERSE_PROXY_AUTH}
      PAPERLESS_URL: ${PAPERLESS_URL}
      PAPERLESS_CSRF_TRUSTED_ORIGINS: ${PAPERLESS_CSRF_TRUSTED_ORIGINS}
      PAPERLESS_CORS_ALLOWED_HOSTS: ${PAPERLESS_CORS_ALLOWED_HOSTS}
      PAPERLESS_TIME_ZONE: ${PAPERLESS_TIME_ZONE}
      PAPERLESS_OCR_LANGUAGE: ${PAPERLESS_OCR_LANGUAGE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless-ngx-insecure.rule=Host(`paperless-ngx.mistyfumes.dev`)"
      - "traefik.http.routers.paperless-ngx-insecure.entrypoints=http"
      - "traefik.http.routers.paperless-ngx-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.paperless-ngx-secure.rule=Host(`paperless-ngx.mistyfumes.dev`)"
      - "traefik.http.routers.paperless-ngx-secure.entrypoints=https"
      - "traefik.http.routers.paperless-ngx-secure.tls=true"
      - "traefik.http.routers.paperless-ngx-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.paperless-ngx.loadbalancer.server.port=8000"
    networks:
      - frontend
      - default

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.25
    restart: unless-stopped
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - default

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - default

networks:
  frontend:
    external: true