apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - templates/
configMapGenerator:
  - name: authentik-values
    namespace: default
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true