services:
  server:
    image: docker.gitea.com/gitea:1.25.4-rootless
    environment:
      - GITEA__database__DB_TYPE=${GITEA__database__DB_TYPE}
      - GITEA__database__HOST=${GITEA__database__HOST}
      - GITEA__database__NAME=${GITEA__database__NAME}
      - GITEA__database__USER=${GITEA__database__USER}
      - GITEA__database__PASSWD=${GITEA__database__PASSWD}
    restart: always
    volumes:
      - /mnt/docker-nfs/volumes/gitea-data/data:/var/lib/gitea
      - /mnt/docker-nfs/volumes/gitea-data/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    depends_on:
      - db

  runner:
    image: gitea/act_runner:latest
    container_name: gitea_runner
    restart: always
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      - /mnt/docker-nfs/volumes/gitea-data/runner/config.yaml:/config.yaml
      - /mnt/docker-nfs/volumes/gitea-data/runner/data:/data
    environment:
      - TZ=America/Denver
      - CONFIG_FILE=/config.yaml
      - GITEA_INSTANCE_URL=http://192.168.1.213:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER_TOKEN}
      - GITEA_RUNNER_NAME=homelab-cicd

  db:
    image: docker.io/library/postgres:14
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /mnt/docker-nfs/volumes/gitea-data/postgres:/var/lib/postgresql/data