services:
  gluetun:
    image: qmcgaw/gluetun:3.41.0
    container_name: gluetun
    # line above must be uncommented to allow external containers to connect.
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8045:8045    # ADD: qBittorrent WebUI
      - 6881:6881     # ADD: qBittorrent
      - 6881:6881/udp # ADD: qBittorrent      
    volumes:
      - /mnt/docker-nfs/volumes/gluetun-data:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      # # OpenVPN:
      # - OPENVPN_USER=
      # - OPENVPN_PASSWORD=
      # Wireguard:
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      # Timezone for accurate log times
      - TZ=America/Denver
      # Server list updater
      # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#update-the-vpn-servers-list
      - UPDATER_PERIOD=
    restart: unless-stopped 

  qbittorrent:
    image: linuxserver/qbittorrent:5.1.4-r1-ls437@sha256:f430d70c70d1547fded30fbc3181c4750cef354212a5138ab754eba9ba8bd9e1
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8045
    volumes:
      - /mnt/docker-nfs/volumes/qbittorrent-data:/config
      - /mnt/octapool-nfs/downloads:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0.5236-ls135@sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/docker-nfs/volumes/arr-stack-data/prowlarr-config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls290@sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/docker-nfs/volumes/arr-stack-data/radarr-config:/config
      - /mnt/octapool-nfs/blu-ray:/data/blu-ray
      - /mnt/octapool-nfs/dvds:/data/dvds      
      - /mnt/octapool-nfs/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls301@sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - /mnt/docker-nfs/volumes/arr-stack-data/sonarr-config:/config
      - /mnt/octapool-nfs/tv:/data/tv
      - /mnt/octapool-nfs/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:2.7.3
    init: true
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Denver
      - PORT=5055
    ports:
      - 5055:5055
    volumes:
      - /mnt/docker-nfs/volumes/arr-stack-data/jellyseerr-config:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped

  wizarr:
    container_name: wizarr
    image: ghcr.io/wizarrrr/wizarr:2025.12.0
    ports:
      - 5690:5690
    volumes:
      - /mnt/docker-nfs/volumes/arr-stack-data/wizarr-config:/data
    environment:
      - PUID=1000 #Set UID
      - PGID=1000 #Set GID
      - DISABLE_BUILTIN_AUTH=false #Set to true ONLY if you are using another auth provider (Authelia, Authentik, etc)
      - TZ=America/Denver #Set your timezone here
    restart: unless-stopped