services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-nfs/volumes/portainer-data:/data
    # ports:
    #   - 9443:9443
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-insecure.rule=Host(`portainer.mistyfumes.dev`)
      - traefik.http.routers.portainer-insecure.entrypoints=http
      - traefik.http.routers.portainer-insecure.middlewares=https-redirect@file
      - traefik.http.routers.portainer-secure.rule=Host(`portainer.mistyfumes.dev`)
      - traefik.http.routers.portainer-secure.entrypoints=https
      - traefik.http.routers.portainer-secure.tls=true
      - traefik.http.routers.portainer-secure.tls.certresolver=cloudflare
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      - frontend

networks:
  frontend:
    external: true