services:
  navidrome:
    image: deluan/navidrome:0.60.3@sha256:a5dce8f33304714dd138e870cca0dcab3d937ca236be1a9f2b97da009d1a0048
    user: 1000:1000
    # ports:
    #   - 4533:4533
    restart: unless-stopped
    volumes:
      - "/mnt/docker-nfs/volumes/navidrome-data:/data"
      - "/mnt/octapool-nfs/music:/music:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.navidrome-insecure.rule=Host(`navidrome.mistyfumes.dev`)"
      - "traefik.http.routers.navidrome-insecure.entrypoints=http"
      - "traefik.http.routers.navidrome-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.navidrome-secure.rule=Host(`navidrome.mistyfumes.dev`)"
      - "traefik.http.routers.navidrome-secure.entrypoints=https"
      - "traefik.http.routers.navidrome-secure.tls=true"
      - "traefik.http.routers.navidrome-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.navidrome.loadbalancer.server.port=4533"
    networks:
      - frontend

networks:
  frontend:
    external: true