services:
  metube:
    image: alexta69/metube:2026.01.11@sha256:dbbf9a25660b6255cc0726a00c06cf2968941803e29813e1d23863919794713c
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - 8081:8081
    volumes:
      - /mnt/docker-nfs/volumes/metube-downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube-insecure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-insecure.entrypoints=http"
      - "traefik.http.routers.metube-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.metube-secure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-secure.entrypoints=https"
      - "traefik.http.routers.metube-secure.tls=true"
      - "traefik.http.routers.metube-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
    networks:
      - frontend

networks:
  frontend:
    external: true