services:
  metube:
    image: alexta69/metube:2026.02.14@sha256:eddc5430c1e3299f2df3a3c413af7b50fdbcbb12c7065fe32d29b4bc83557aac
    container_name: metube
    restart: unless-stopped
    # ports:
    #   - 8081:8081
    volumes:
      - /mnt/docker-nfs/volumes/metube-downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube-insecure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-insecure.entrypoints=http"
      - "traefik.http.routers.metube-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.metube-secure.rule=Host(`metube.mistyfumes.dev`)"
      - "traefik.http.routers.metube-secure.entrypoints=https"
      - "traefik.http.routers.metube-secure.tls=true"
      - "traefik.http.routers.metube-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"
    networks:
      - frontend

networks:
  frontend:
    external: true