services:
  bytestash:
    container_name: bytestash
    image: ghcr.io/jordan-dalby/bytestash:1.5.11@sha256:0b18d858623855e34cf14354c360e155cb742c46c17e843a85b978ce8af83396
    # ports:
    #   - 5000:5000
    volumes:
      - /mnt/docker-nfs/volumes/bytestash-data:/data/snippets
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bytestash-insecure.rule=Host(`bytestash.mistyfumes.dev`)"
      - "traefik.http.routers.bytestash-insecure.entrypoints=http"
      - "traefik.http.routers.bytestash-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.bytestash-secure.rule=Host(`bytestash.mistyfumes.dev`)"
      - "traefik.http.routers.bytestash-secure.entrypoints=https"
      - "traefik.http.routers.bytestash-secure.tls=true"
      - "traefik.http.routers.bytestash-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.bytestash.loadbalancer.server.port=5000"
    networks:
      - frontend

networks:
  frontend:
    external: true