apiVersion: v1
kind: Service
metadata:
  name: adguard-prod
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard-prod
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.218
  ports:
  - port: 80
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-prod-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`adguard.mistyfumes.dev`)
    kind: Rule
    services:
    - name: adguard-prod
      port: 80
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true