apiVersion: v1
kind: Service
metadata:
  name: gitea-demo-1
  namespace: default
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
  - name: ssh
    port: 2222
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gitea-demo-1
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.213
  ports:
  - name: http
    port: 3000
  - name: ssh
    port: 2222
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: gitea-demo-1-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`gitea-demo-1.mistyfumes.dev`)
    kind: Rule
    services:
    - name: gitea-demo-1
      port: 3000
      serversTransport: insecure-transport
  tls:
    secretName: dev-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: gitea-demo-1-ssh
  namespace: default
spec:
  entryPoints:
    - ssh
  routes:
  - match: HostSNI(`*`)
    services:
    - name: gitea-demo-1
      port: 2222
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true