apiVersion: v1
kind: Service
metadata:
  name: open-webui-demo-1
  namespace: default
spec:
  ports:
  - port: 3150
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: open-webui-demo-1
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.213
  ports:
  - port: 3150
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: open-webui-demo-1-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`open-webui.dev.mistyfumes.dev`)
    kind: Rule
    services:
    - name: open-webui-demo-1
      port: 3150
      scheme: https
      serversTransport: insecure-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true