apiVersion: v1
kind: Service
metadata:
  name: opnsense-prod-1
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opnsense-prod-1
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.1
  ports:
  - port: 443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opnsense-prod-1-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`opnsense.mistyfumes.dev`)
    kind: Rule
    services:
    - name: opnsense-prod-1
      port: 443
      scheme: https
      serversTransport: insecure-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true