apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: default
spec:
  ports:
  - port: 8000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: paperless
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.213
  ports:
  - port: 8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`paperless.mistyfumes.dev`)
    kind: Rule
    services:
    - name: paperless
      port: 8000
      scheme: https
      serversTransport: insecure-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true
