apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: default
spec:
  ports:
  - port: 9696
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prowlarr
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.213
  ports:
  - port: 9696
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prowlarr.mistyfumes.dev`)
    kind: Rule
    services:
    - name: prowlarr
      port: 9696
      serversTransport: insecure-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true