apiVersion: v1
kind: Service
metadata:
  name: prx-demo-1
  namespace: default
spec:
  ports:
  - port: 8006
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prx-demo-1
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.128
  ports:
  - port: 8006
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prx-demo-1-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prx-demo-1.mistyfumes.dev`)
    kind: Rule
    services:
    - name: prx-demo-1
      port: 8006
      scheme: https
      serversTransport: insecure-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: default
spec:
  insecureSkipVerify: true