apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: default
spec:
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: wazuh
  namespace: default
subsets:
- addresses:
  - ip: 192.168.1.225
  ports:
  - port: 443
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: wazuh-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`wazuh.mistyfumes.dev`)
    kind: Rule
    services:
    - name: wazuh
      port: 443
      serversTransport: wazuh-transport
  tls:
    secretName: prod-mistyfumes-tls
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: wazuh-transport
  namespace: default
spec:
  insecureSkipVerify: true