apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: metube-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`metube.mistyfumes.dev`)
      kind: Rule
      services:
        - name: metube
          port: 8081
  tls:
    secretName: prod-mistyfumes-tls