apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard-webui
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`adguard.dev.mistyfumes.dev`)
      kind: Rule
      services:
        - name: adguard
          port: 3000
  tls:
    secretName: dev-mistyfumes-tls