services:
  traefik:
    image: traefik:v3.6
    container_name: traefik-prod-1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/docker-nfs/volumes/traefik-data/config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - /mnt/docker-nfs/volumes/traefik-data/config/dynamic.yaml:/etc/traefik/dynamic.yaml:ro
      - /mnt/docker-nfs/volumes/traefik-data/data/certs/:/var/traefik/certs/:rw
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-http.rule=Host(`traefik-prod-1.mistyfumes.dev`)"
      - "traefik.http.routers.traefik-http.entrypoints=http"
      - "traefik.http.routers.traefik-http.middlewares=traefik-https-redirect"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik-https.rule=Host(`traefik-prod-1.mistyfumes.dev`)"
      - "traefik.http.routers.traefik-https.entrypoints=https"
      - "traefik.http.routers.traefik-https.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-https.tls.domains[0].main=mistyfumes.dev"
      - "traefik.http.routers.traefik-https.tls.domains[0].sans=*.mistyfumes.dev"
      - "traefik.http.routers.traefik-https.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"

networks:
  frontend:
    external: true