services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3100:3000
    volumes:
      - /mnt/docker-nfs/volumes/homepage-data/config:/app/config
      - /mnt/docker-nfs/volumes/homepage-data/images:/app/public/images
      - /mnt/docker-nfs/volumes/homepage-data/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.mistyfumes.dev
      - PUID=1000
      - PGID=1000
    restart: unless-stopped