services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.10.0@sha256:f04905d7698bb9153866645b669cdb198ee35f1bfb1e04e2b19a55520fea6261
    container_name: homepage
    # ports:
    #   - 3000:3000
    volumes:
      - /mnt/docker-nfs/volumes/homepage-data/config:/app/config
      - /mnt/docker-nfs/volumes/homepage-data/images:/app/public/images
      - /mnt/docker-nfs/volumes/homepage-data/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.mistyfumes.dev
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage-insecure.rule=Host(`homepage.mistyfumes.dev`)"
      - "traefik.http.routers.homepage-insecure.entrypoints=http"
      - "traefik.http.routers.homepage-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.homepage-secure.rule=Host(`homepage.mistyfumes.dev`)"
      - "traefik.http.routers.homepage-secure.entrypoints=https"
      - "traefik.http.routers.homepage-secure.tls=true"
      - "traefik.http.routers.homepage-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
    networks:
      - frontend

networks:
  frontend:
    external: true