services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      TZ: "America/Denver"
      DB_POSTGRES_HOST: ${DB_POSTGRES_HOST}
      DB_POSTGRES_PORT: ${DB_POSTGRES_PORT}
      DB_POSTGRES_USER: ${DB_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      DB_POSTGRES_NAME: ${DB_POSTGRES_NAME}
      #DISABLE_IPV6: ${DISABLE_IPV6}
    volumes:
      - /mnt/docker-nfs/volumes/nginx-data/nginx-npm-data:/data
      - /mnt/docker-nfs/volumes/nginx-data/nginx-npm-letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - npm_bridge      

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /mnt/docker-nfs/volumes/nginx-data/nginx-npm-postgres:/var/lib/postgresql/data
    networks:
      - npm_bridge
    ports:
      - '5433:5432'
    restart: always

networks:
  npm_bridge:
    external: true