apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - actualbudget-pvc.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: actual-budget-values
    namespace: default
    files:
      - values.yaml