image:
  repository: actualbudget/actual-server
  tag: "26.2.0@sha256:c34346f87725b9cce5dca5af1a2a9b989127d592cc4c6af5cf4652d4a86def90"
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

files:
  server: /data/server-files
  user: /data/user-files

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: actualbudget.mistyfumes.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: prod-mistyfumes-tls
      hosts:
        - actualbudget.mistyfumes.dev

persistence:
  enabled: true
  existingClaim: actualbudget-nfs-pvc