services:
  adguard-server:
    container_name: adguard_server
    image: adguard/adguardhome:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
    volumes:
      - /opt/adguardhome/work:/opt/adguardhome/work
      - /mnt/docker-nfs/volumes/adguardhome/conf:/opt/adguardhome/conf
    restart: always