apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: termix-ssh
  namespace: flux-system
spec:
  interval: 15m
  targetNamespace: default
  chart:
    spec:
      chart: ./kubernetes/services/termix-ssh/my-termix-ssh
      valuesFiles:
        - ./kubernetes/services/termix-ssh/my-termix-ssh/prod-values.yaml
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system