apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: immich-db
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: immich-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: immich-database
      volumes:
        - name: immich-database
          persistentVolumeClaim:
            claimName: immich-db-nfs-pvc