apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-db
  template:
    metadata:
      labels:
        app: immich-db
    spec:
      containers:
        - name: immich-db
          image: ghcr.io/immich-app/postgres:16-vectorchord0.4.3-pgvectors0.2.0@sha256:1a078b237c1d9b420b0ee59147386b4aa60d3a07a8e6a402fc84a57e41b043a4
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: immich-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: immich-database
      volumes:
        - name: immich-database
          persistentVolumeClaim:
            claimName: immich-db-nfs-pvc