apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - immich-postgres-deployment.yaml
  - immich-postgres-pvc.yaml
  - immich-postgres-svc.yaml
  - immich-sealed-secret.yaml
  - immich-uploads-pvc.yaml
  - octapool-images-pvc.yaml
  - octapool-photography-pvc.yaml