apiVersion: v1
kind: PersistentVolume
metadata:
  name: octapool-images-library-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - addr=192.168.1.130
  nfs:
    server: 192.168.1.130
    path: /mnt/octaPool/images/photos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octapool-images-library-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: octapool-images-library-pv