services:
  web:
    image: ghcr.io/karakeep-app/karakeep:0.30.0@sha256:a2e188284cc3350db3246664954d1bff223c67be98c3a4de782b159f864e7c07
    restart: unless-stopped
    volumes:
      - /mnt/docker-nfs/volumes/karakeep-data:/data
    # ports:
    #   - 3000:3000
    env_file: .env
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data # DON'T CHANGE THIS. If you want to mount a custom directory, change the volume mapping above instead.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.karakeep-insecure.rule=Host(`karakeep.mistyfumes.dev`)"
      - "traefik.http.routers.karakeep-insecure.entrypoints=http"
      - "traefik.http.routers.karakeep-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.karakeep-secure.rule=Host(`karakeep.mistyfumes.dev`)"
      - "traefik.http.routers.karakeep-secure.entrypoints=https"
      - "traefik.http.routers.karakeep-secure.tls=true"
      - "traefik.http.routers.karakeep-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.karakeep.loadbalancer.server.port=3000"
    networks:
      - default
      - frontend

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - default

  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    env_file: .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - /mnt/docker-nfs/volumes/karakeep-data/meilisearch:/meili_data
    networks:
      - default

networks:
  frontend:
    external: true