services:
  postgres:
    image: postgres:16-alpine
    restart: always
    env_file: .env
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data/pgdata:/var/lib/postgresql/data
    networks:
      - default

  linkwarden:
    env_file: .env
    restart: always
    image: ghcr.io/linkwarden/linkwarden:v2.13.5@sha256:5b8e231169f6819d1a1e5a9f4771c9179108694c60da1e34fc4a0ea780f70079
    # ports:
    #   - 3000:3000
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data:/data/data
    depends_on:
      - postgres
      - meilisearch
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkwarden-insecure.rule=Host(`linkwarden.mistyfumes.dev`)"
      - "traefik.http.routers.linkwarden-insecure.entrypoints=http"
      - "traefik.http.routers.linkwarden-insecure.middlewares=https-redirect@file"
      - "traefik.http.routers.linkwarden-secure.rule=Host(`linkwarden.mistyfumes.dev`)"
      - "traefik.http.routers.linkwarden-secure.entrypoints=https"
      - "traefik.http.routers.linkwarden-secure.tls=true"
      - "traefik.http.routers.linkwarden-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.linkwarden.loadbalancer.server.port=3000"
    networks:
      - default
      - frontend

  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    env_file:
      - .env
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data/meili_data:/meili_data
    networks:
      - default

networks:
  frontend:
    external: true