services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data/pgdata:/var/lib/postgresql/data
      
  linkwarden:
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - MEILI_ADDR=http://meilisearch:7700
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    restart: always
    image: ghcr.io/linkwarden/linkwarden:v2.13.5@sha256:5b8e231169f6819d1a1e5a9f4771c9179108694c60da1e34fc4a0ea780f70079
    ports:
      - 3900:3000
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data:/data/data
    depends_on:
      - postgres
      - meilisearch
      
  meilisearch:
    image: getmeili/meilisearch:v1.12.8
    restart: always
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - /mnt/docker-nfs/volumes/linkwarden-data/meili_data:/meili_data